---

- hosts: all
  become: true
  tasks:
 
  - name: update respository index
    yum:
      update_cache: yes     
        
        
  - name: remove httpd package
    yum:
      name: httpd
      state: absent


