---

- hosts: all
  become: true
  pre_tasks:
  
  - name: install updates (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes  
    when: ansible_distribution == "CentOS"   

- hosts: web_servers
  become: true
  tasks:
        
  - name: install httpd and php package for Centos
    tags: apache,centos, httpd
    yum:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
  
  - name: copy default html file for site
    tags: apacche,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644  

- hosts: db_servers
  become: true
  tasks:
  - name: install mariadb package (CentosOS)
    tags: centos,db,mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: file_servers
  become: true
  tasks:
  - name: install samba package
    yum:
      name: samba
      state: latest 
